CC_TEXTURES_DIR: '/home/bproc/Datasets/cc_textures'
# CC_TEXTURES_DIR: '/home/shq/Datasets/cc_textures'
OUTPUT_DIR: '/home/bproc/BlenderProc/output/custom'
# OUTPUT_DIR: '/home/shq/Projects/my/BlenderProc/output/custom'
ENABLE_DEPTH: true
DEPTH_SCALE: 10000
NUM_SCENES: 5
NUM_CAMERAS_PER_SCENE: 5

OBJECT:
    FILE: "/home/bproc/Datasets/BOP/tless/models_cad/obj_000001.ply"
    # FILE: "/home/shq/Datasets/BOP/tless/models_cad/obj_000001.ply"
    # m / mm / auto
    UNIT: 'auto'
    DECIMATION: 15000  # -1 for no decimation
    MOVE_TO_MASS_CENTER: true
    # auto / smooth / flat
    SHADING_MODE: 'auto'
    POSE_SAMPLER:
        MIN_NUM: 10
        MAX_NUM: 10
        MIN_HEIGHT: 1
        MAX_HEIGHT: 1.5
        ENABLE_PHYSICS: true
        PHYSICS:
            MIN_SIMULATION_TIME: 3
            MAX_SIMULATION_TIME: 10
            SUBSTEPS_PER_FRAME: 15
            SOLVER_ITERS: 15
    MATERIAL_SAMPLER:
        MIN_GRAY: 0.0
        MAX_GRAY: 1.0
        MIN_ROUGHNESS: 0
        MAX_ROUGHNESS: 0.5
        MIN_SPECULAR: 0.3
        MAX_SPECULAR: 1.0
        MIN_METALLIC: 0
        MAX_METALLIC: 1.0

TOTE:
    # auto / scalar
    WIDTH: auto
    LENGTH: auto
    HEIGHT: 0.5
    WALL_VISIBLE: false
    RANDOM_TEXTURE: true

CAMERA:
    INTRINSICS:
        FX: 1000
        FY: 1000
        PPX: 640
        PPY: 480
        WIDTH: 1280
        HEIGHT: 960
        RANDOM_PERCENT: 5
    POSE_SAMPLER:
        MIN_HEIGHT: 0.6
        MAX_HEIGHT: 0.6
        MIN_ELEVATION: 75
        MAX_ELEVATION: 90
    
LIGHT:
    MIN_NUM: 1
    MAX_NUM: 3
    MIN_ENERGY: 1
    MAX_ENERGY: 20
    MIN_HEIGHT: 0.6
    MAX_HEIGHT: 0.8
    MIN_ELEVATION: 30
    MAX_ELEVATION: 90
