#!/bin/bash
CURRENT_DIR=$(dirname $(realpath $0))
PROJECT_DIR=$(dirname $CURRENT_DIR)

IMAGE_NAME=blenderproc/gdrn:latest
CONTAINER_NAME=blenderproc
CONTAINER_HOME=/home/bproc

MODELS_ROOT=/home/shq/Data/VG1207/hard-example
TEXTURES_ROOT=/home/shq/Datasets/cc_textures

if [ "$(docker ps -aq -f name=$CONTAINER_NAME)" ]; then
    docker rm -f $CONTAINER_NAME
fi
docker run -it \
    --rm \
    --gpus '"device=0"' \
    --name $CONTAINER_NAME \
    --volume="$MODELS_ROOT:$CONTAINER_HOME/Datasets/models:ro" \
    --volume="$TEXTURES_ROOT:$CONTAINER_HOME/Datasets/cc_textures:ro" \
    --volume="$PROJECT_DIR:$CONTAINER_HOME/BlenderProc:rw" \
    --volume="/dev/shm:/dev/shm:rw" \
    --network=host \
    $IMAGE_NAME \
    /bin/bash -c './BlenderProc/run_gdrn_custom.sh'
    # /bin/bash
